- name: my variables ansible file
  hosts: all
  vars:
    pokemon: "pikachu"
  tasks:
   - name: print msg
     debug:
       msg: my "{{pokemon}}"
   - name: print msg
     debug:
       msg: "{{pokemon}}"
   - name: local variables
    debug: 
      msg: "{{pokemon}}"
      


#global variables
#local variables
#file
#prompt
#cli
#host