- name: my variables ansible file
  hosts: all
  vars:
   - 
  tasks:
   - name: print msg
     debug:
       msg: "hello this is ansible"
   - name: print msg
     debug:
       msg: "how are you"


#global variables
#local variables
#file
#prompt
#cli
#host