- name: my variables ansible file
  hosts: all
  # vars:               #global variable
  #   pokemon: pikachu
  vars_files:
   - ./var.txt
  tasks:
   - name: print msg
     debug:
       msg: my "{{pokemon}}"
   - name: print msg
     debug:
       msg: "{{pokemon}}"
   - name: local variables
     debug: 
       msg: "{{pokemon}}"
     vars:
       pokemon: pichu
   - name: run command
     shell: hostname
     register: hostname 
   - name: print prompt
     
     debug:
        msg: "{{name}}" 
  vars_prompt:
    - name: prompt-variable
      prompt: what is your name?
      private: false
      
    


#global variables
#local variables
#file
#prompt
#cli
#host