- name: my variables ansible file
  hosts: all
  tasks:
   - name: print msg
     debug:
       msg: "hello this is ansible"
   - name: print msg
     debug:
       msg: "how are you"


#global variables
#local variables
#