- name: this is role 
  hosts: all
  tasks:
    - name: install httpd
      package:
        - name: "{{app}}"
          state: latest
      when: ansible_os_family == "RedHat"
    # - name: start the httpd
    #   systemd:
    #     - name: "{{app}}"
    #       state: restarted
    #   when: ansible_os_family == "RedHat"
