- name: this is role 
  hosts: all
  tasks:
    - name: install httpd
      package:
        - name: httpd
          state: latest
      when: ansible_os_family == "RedHat"
      systemd:
        - name: httpd
          state: started
